"""Pure employee Block Kit views over PeopleFlow HTTP API records.

Home, request forms, and messages have separate modules; the public functions
remain available here. No renderer performs API calls or opens business data.
Literal text primitives prevent user content from creating mentions or links.
Chat answers have no controls. Legacy source/feedback forms remain available
for already-posted messages and dedicated history.
"""

from .home import (
    home_view,
)
from .messages import (
    answer_blocks,
    conversation_view,
    error_blocks,
    feedback_view,
    help_blocks,
    loading_blocks,
    notice_view,
    question_view,
    sources_view,
    state_blocks,
    text_blocks,
)
from .primitives import (
    ACTIVITY_PAGE_SIZE,
    ANSWER_TEXT_BLOCKS,
    ASK_QUESTION,
    CANCEL_REQUEST,
    COMMENT_MAX_LENGTH,
    CONTINUE_CONVERSATION,
    CONVERSATION_DETAIL,
    CONVERSATION_PAGE,
    CONVERSATION_PAGE_SIZE,
    DELETE_CONVERSATION,
    EDIT_REQUEST,
    EMPLOYEE_HOME,
    FEEDBACK_HELPFUL,
    FEEDBACK_SUBMIT,
    FEEDBACK_UNHELPFUL,
    HOME_PAGE_SIZE,
    HOME_SECTION,
    INPUT_ACTION,
    NEW_PTO,
    NEW_REQUEST,
    NEW_SICK_LEAVE,
    OPEN_CHAT,
    OPEN_CONVERSATION,
    OPEN_REQUEST,
    OPEN_SLACK_CONVERSATION,
    QUESTION_MAX_LENGTH,
    QUESTION_SUBMIT,
    REQUEST_DETAIL,
    REQUEST_DETAIL_PAGE,
    REQUEST_FIELD_CHANGED,
    REQUEST_SUBMIT,
    REQUEST_TYPE_SUBMIT,
    SELECT_REQUEST,
    SHOW_CONVERSATIONS,
    SHOW_HOME,
    SHOW_REQUESTS,
    SOURCE_EXCERPT_LIMIT,
    SOURCE_LIMIT,
    SOURCES,
    TEXT_LIMIT,
    VIEW_SOURCES,
)
from .requests import (
    notification_blocks,
    request_blocks,
    request_detail_view,
    request_form,
    request_type_view,
    workflow_answer_text,
)

__all__ = [
    "ACTIVITY_PAGE_SIZE",
    "ANSWER_TEXT_BLOCKS",
    "ASK_QUESTION",
    "CANCEL_REQUEST",
    "COMMENT_MAX_LENGTH",
    "CONTINUE_CONVERSATION",
    "CONVERSATION_DETAIL",
    "CONVERSATION_PAGE",
    "CONVERSATION_PAGE_SIZE",
    "DELETE_CONVERSATION",
    "EDIT_REQUEST",
    "EMPLOYEE_HOME",
    "FEEDBACK_HELPFUL",
    "FEEDBACK_SUBMIT",
    "FEEDBACK_UNHELPFUL",
    "HOME_PAGE_SIZE",
    "HOME_SECTION",
    "INPUT_ACTION",
    "NEW_PTO",
    "NEW_REQUEST",
    "NEW_SICK_LEAVE",
    "OPEN_CHAT",
    "OPEN_CONVERSATION",
    "OPEN_REQUEST",
    "OPEN_SLACK_CONVERSATION",
    "QUESTION_MAX_LENGTH",
    "QUESTION_SUBMIT",
    "REQUEST_DETAIL",
    "REQUEST_DETAIL_PAGE",
    "REQUEST_FIELD_CHANGED",
    "REQUEST_SUBMIT",
    "REQUEST_TYPE_SUBMIT",
    "SELECT_REQUEST",
    "SHOW_CONVERSATIONS",
    "SHOW_HOME",
    "SHOW_REQUESTS",
    "SOURCES",
    "SOURCE_EXCERPT_LIMIT",
    "SOURCE_LIMIT",
    "TEXT_LIMIT",
    "VIEW_SOURCES",
    "answer_blocks",
    "conversation_view",
    "error_blocks",
    "feedback_view",
    "help_blocks",
    "home_view",
    "loading_blocks",
    "notice_view",
    "notification_blocks",
    "question_view",
    "request_blocks",
    "request_detail_view",
    "request_form",
    "request_type_view",
    "sources_view",
    "state_blocks",
    "text_blocks",
    "workflow_answer_text",
]
