import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { AlertTriangle, BarChart3, BookOpen, CheckCircle2, FileText, MessageSquareWarning, RefreshCw, Settings2, ThumbsUp } from "lucide-react";
import { useState } from "react";
import { api } from "../../api/client";
import type { DocumentItem, Metrics } from "../../api/types";
import { useAuth } from "../../app/providers";
import { Shell } from "../../components/Shell";
import { Badge, Button, Card, fieldClass, statusTone } from "../../components/ui";

type Section="overview"|"documents"|"indexing"|"unanswered"|"feedback"|"settings";
export function KnowledgePage(){const{token}=useAuth();const[section,setSection]=useState<Section>("overview");const metrics=useQuery({queryKey:["metrics"],queryFn:()=>api<{metrics:Metrics}>("/api/v1/admin/metrics",token)});const items:[Section,string,React.ReactNode][]=[["overview","Overview",<BarChart3/>],["documents","Documents",<BookOpen/>],["indexing","Indexing",<RefreshCw/>],["unanswered","Unanswered",<MessageSquareWarning/>],["feedback","Feedback",<ThumbsUp/>],["settings","System settings",<Settings2/>]];const sidebar=<nav className="space-y-1">{items.map(([id,label,icon])=><button key={id} onClick={()=>setSection(id)} className={`focus-ring flex w-full items-center gap-3 rounded-xl px-3 py-3 text-sm ${section===id?"bg-lime-soft text-lime":"text-muted hover:bg-raised hover:text-cream"} [&>svg]:h-4 [&>svg]:w-4`}>{icon}{label}</button>)}</nav>;
 return <Shell sidebar={sidebar} eyebrow="Knowledge operations"><div className="mx-auto max-w-7xl p-4 sm:p-8"><div className="mb-8 flex items-end justify-between"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-lime">Knowledge health</p><h1 className="mt-3 text-4xl font-medium tracking-[-.035em]">{items.find(x=>x[0]===section)?.[1]}</h1></div><Button tone="secondary" onClick={()=>metrics.refetch()}><RefreshCw size={15}/>Refresh</Button></div>{section==="overview"&&<Overview metrics={metrics.data?.metrics}/>} {section==="documents"&&<Documents/>}{section==="indexing"&&<Indexing/>}{section==="unanswered"&&<Unanswered/>}{section==="feedback"&&<Feedback metrics={metrics.data?.metrics}/>} {section==="settings"&&<Settings/>}</div></Shell>}
function Overview({metrics:m}:{metrics?:Metrics}){const cards=[["Questions",m?.questions??0,"All assistant conversations",<BarChart3/>],["Grounded rate",`${m?.grounded_answer_rate??0}%`,"Answers with document evidence",<CheckCircle2/>],["Unanswered",m?.unanswered_questions??0,"Knowledge gaps to resolve",<AlertTriangle/>],["Positive feedback",`${m?.positive_feedback_rate??0}%`,"Helpful response ratings",<ThumbsUp/>],["Requests created",m?.requests_created??0,"Employee actions started",<FileText/>],["Approved",m?.requests_approved??0,"Requests approved or complete",<CheckCircle2/>]];return <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{cards.map(([label,value,copy,icon])=><Card key={String(label)} className="min-h-40"><div className="flex items-start justify-between"><span className="text-sm font-semibold">{label}</span><span className="text-lime [&>svg]:h-5 [&>svg]:w-5">{icon}</span></div><strong className="mt-7 block text-4xl font-medium tracking-tight">{value}</strong><p className="mt-2 text-xs text-muted">{copy}</p></Card>)}</div>}
function Documents(){const{token}=useAuth();const qc=useQueryClient();const docs=useQuery({queryKey:["documents"],queryFn:()=>api<{documents:DocumentItem[]}>("/api/v1/documents",token)});const indexing=useMutation({mutationFn:(id:string)=>api(`/api/v1/documents/${id}/index`,token,{method:"POST"}),onSuccess:()=>qc.invalidateQueries({queryKey:["documents"]})});return <Card className="overflow-hidden p-0"><div className="border-b border-line p-5"><h2 className="font-semibold">Source library</h2><p className="mt-1 text-xs text-muted">Index health, ownership metadata, and retrieval coverage.</p></div><div className="divide-y divide-line">{docs.data?.documents.map(d=><div key={d.id} className="grid gap-4 p-5 lg:grid-cols-[1.5fr_.8fr_.55fr_.75fr_auto] lg:items-center"><div><div className="flex items-center gap-2"><FileText size={16} className="text-coral"/><strong className="text-sm">{d.title}</strong></div><p className="mt-1 text-xs text-muted">{d.name}</p>{d.index_error&&<p className="mt-2 text-xs text-danger">{d.index_error}</p>}</div><div><span className="text-[10px] uppercase text-muted">Category</span><p className="mt-1 text-sm">{d.category} · v{d.version}</p></div><div><span className="text-[10px] uppercase text-muted">Chunks</span><p className="mt-1 text-sm font-semibold">{d.chunk_count}</p></div><div><Badge tone={statusTone(d.index_status)}>{d.index_status}</Badge><p className="mt-2 text-[10px] text-muted">{d.indexed_at?new Date(d.indexed_at).toLocaleString():"Never indexed"}</p></div><Button tone="secondary" onClick={()=>indexing.mutate(d.id)} disabled={indexing.isPending}>Index</Button></div>)}</div></Card>}
function Indexing(){const{token}=useAuth();const docs=useQuery({queryKey:["documents"],queryFn:()=>api<{documents:DocumentItem[]}>("/api/v1/documents",token)});const list=docs.data?.documents??[];return <div className="grid gap-4 lg:grid-cols-3"><Card><p className="text-xs uppercase tracking-wider text-muted">Indexed</p><strong className="mt-5 block text-5xl text-lime">{list.filter(x=>x.index_status==="indexed").length}</strong></Card><Card><p className="text-xs uppercase tracking-wider text-muted">Pending</p><strong className="mt-5 block text-5xl text-coral">{list.filter(x=>x.index_status==="pending").length}</strong></Card><Card><p className="text-xs uppercase tracking-wider text-muted">Errors</p><strong className="mt-5 block text-5xl text-danger">{list.filter(x=>x.index_status==="error").length}</strong></Card><Card className="lg:col-span-3"><h2 className="font-semibold">Index activity</h2><div className="mt-4 divide-y divide-line">{list.map(x=><div className="flex items-center justify-between gap-4 py-3" key={x.id}><div><p className="text-sm font-semibold">{x.title}</p><p className="mt-1 text-xs text-muted">{x.chunk_count} chunks · {x.indexed_at?new Date(x.indexed_at).toLocaleString():"not indexed"}</p></div><Badge tone={statusTone(x.index_status)}>{x.index_status}</Badge></div>)}</div></Card></div>}
function Unanswered(){const{token}=useAuth();const q=useQuery({queryKey:["unanswered"],queryFn:()=>api<{questions:{timestamp:string;question:string;assistant:string}[]}>("/api/v1/admin/unanswered",token)});return <div className="space-y-3">{q.data?.questions.map((x,i)=><Card key={`${x.timestamp}-${i}`}><div className="flex gap-3"><AlertTriangle className="mt-1 text-coral" size={18}/><div><strong className="text-sm">{x.question}</strong><p className="mt-2 text-xs leading-5 text-muted">{x.assistant}</p><p className="mt-3 text-[10px] uppercase tracking-wider text-muted">{new Date(x.timestamp).toLocaleString()}</p></div></div></Card>)}{!q.data?.questions.length&&<Empty title="No unanswered questions" copy="New knowledge gaps will appear here automatically."/>}</div>}
function Feedback({metrics:m}:{metrics?:Metrics}){return <div className="grid gap-4 sm:grid-cols-2"><Card><p className="text-xs uppercase tracking-wider text-muted">Positive feedback</p><strong className="mt-6 block text-6xl font-medium text-lime">{m?.positive_feedback_rate??0}%</strong><p className="mt-3 text-sm text-muted">Share of ratings marked helpful.</p></Card><Card><p className="text-xs uppercase tracking-wider text-muted">Feedback signals</p><strong className="mt-6 block text-6xl font-medium">{Number(m?.feedback??0)+Number(m?.assistant_feedback??0)}</strong><p className="mt-3 text-sm text-muted">Workflow and answer feedback combined.</p></Card></div>}
function Settings(){const{token}=useAuth();const[prompt,setPrompt]=useState("");const load=useQuery({queryKey:["system-prompt"],queryFn:()=>api<{system_prompt:string}>("/api/v1/admin/system-prompt",token)});if(load.data&&!prompt)setPrompt(load.data.system_prompt);const save=useMutation({mutationFn:()=>api("/api/v1/admin/system-prompt",token,{method:"PUT",body:JSON.stringify({system_prompt:prompt})})});return <Card className="max-w-3xl"><h2 className="font-semibold">Assistant behavior</h2><p className="mt-2 text-sm leading-6 text-muted">Advanced setting. Document quality and unanswered questions should be reviewed before changing this prompt.</p><textarea className={`${fieldClass} mt-6 min-h-56 font-mono text-xs leading-6`} value={prompt} onChange={e=>setPrompt(e.target.value)}/><div className="mt-4 flex justify-end"><Button onClick={()=>save.mutate()} disabled={save.isPending}>{save.isSuccess?"Saved":"Save settings"}</Button></div></Card>}
function Empty({title,copy}:{title:string;copy:string}){return <Card className="grid min-h-64 place-items-center text-center"><div><CheckCircle2 className="mx-auto text-lime"/><h3 className="mt-3 font-semibold">{title}</h3><p className="mt-2 text-sm text-muted">{copy}</p></div></Card>}
