import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { CheckCircle2, Clock3, Filter, Inbox, Search, XCircle } from "lucide-react";
import { useMemo, useState } from "react";
import { api } from "../../api/client";
import type { RequestDetail, WorkflowRequest } from "../../api/types";
import { useAuth } from "../../app/providers";
import { Shell } from "../../components/Shell";
import { Badge, Button, Card, Drawer, fieldClass, statusTone } from "../../components/ui";

export function ManagerPage(){const{token}=useAuth();const qc=useQueryClient();const[status,setStatus]=useState("all");const[search,setSearch]=useState("");const[selected,setSelected]=useState<string|null>(null);
 const requests=useQuery({queryKey:["manager-requests"],queryFn:()=>api<{requests:WorkflowRequest[]}>("/api/v1/requests",token)});
 const data=requests.data?.requests??[];const counts={pending:data.filter(r=>["submitted","in_review"].includes(r.status)).length,approved:data.filter(r=>["approved","completed"].includes(r.status)).length,declined:data.filter(r=>r.status==="declined").length};
 const rows=useMemo(()=>data.filter(r=>(status==="all"||r.status===status)&&`${r.type_label} ${r.applicant} ${r.comment}`.toLowerCase().includes(search.toLowerCase())),[data,status,search]);
 const sidebar=<><Card className="mb-4 bg-lime-soft"><p className="text-xs font-semibold text-lime">Decision queue</p><p className="mt-2 text-3xl font-medium">{counts.pending}</p><p className="text-xs text-muted">waiting for review</p></Card><p className="px-3 text-xs leading-5 text-muted">Approve with confidence. Declines require a reason and every action stays in the timeline.</p></>;
 return <Shell sidebar={sidebar} eyebrow="Manager inbox"><div className="mx-auto max-w-7xl p-4 sm:p-8"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-lime">Decision workspace</p><h1 className="mt-3 text-4xl font-medium tracking-[-.035em]">Manager inbox</h1><p className="mt-2 text-sm text-muted">Requests that need your judgment, not another spreadsheet.</p></div><div className="flex gap-3"><Metric label="Pending" value={counts.pending} icon={<Clock3/>}/><Metric label="Approved" value={counts.approved} icon={<CheckCircle2/>}/><Metric label="Declined" value={counts.declined} icon={<XCircle/>}/></div></div>
 <Card className="mt-8 p-0 overflow-hidden"><div className="flex flex-col gap-3 border-b border-line p-4 sm:flex-row"><label className="relative flex-1"><Search className="absolute left-3 top-3 text-muted" size={17}/><input className={`${fieldClass} pl-10`} value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search requests"/></label><label className="relative"><Filter className="absolute left-3 top-3 text-muted" size={16}/><select className={`${fieldClass} min-w-44 pl-10`} value={status} onChange={e=>setStatus(e.target.value)}><option value="all">All statuses</option><option value="submitted">Submitted</option><option value="in_review">In review</option><option value="approved">Approved</option><option value="declined">Declined</option></select></label></div>
 <div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left"><thead><tr className="text-[10px] uppercase tracking-wider text-muted">{["Request","Employee","Dates","Status","Created",""].map(x=><th key={x} className="px-5 py-3 font-semibold">{x}</th>)}</tr></thead><tbody>{rows.map(r=><tr key={r.id} className="border-t border-line/70 hover:bg-raised/60"><td className="px-5 py-4"><strong className="text-sm">{r.type_label}</strong><p className="mt-1 max-w-xs truncate text-xs text-muted">{r.comment}</p></td><td className="px-5 py-4 text-sm">{r.applicant}</td><td className="px-5 py-4 text-xs text-muted">{r.start_date??"—"} → {r.end_date??"—"}</td><td className="px-5 py-4"><Badge tone={statusTone(r.status)}>{r.status}</Badge></td><td className="px-5 py-4 text-xs text-muted">{new Date(r.created_at).toLocaleDateString()}</td><td className="px-5 py-4"><Button tone="secondary" onClick={()=>setSelected(r.id)}>Review</Button></td></tr>)}</tbody></table>{!rows.length&&<div className="grid min-h-52 place-items-center text-sm text-muted"><Inbox className="mb-2 mx-auto"/>No requests match this view.</div>}</div></Card></div><DecisionDrawer id={selected} onClose={()=>setSelected(null)} onDone={()=>{qc.invalidateQueries({queryKey:["manager-requests"]});setSelected(null)}}/></Shell>}
function Metric({label,value,icon}:{label:string;value:number;icon:React.ReactNode}){return <Card className="min-w-24 p-3"><span className="text-muted [&>svg]:h-4 [&>svg]:w-4">{icon}</span><strong className="mt-2 block text-xl">{value}</strong><span className="text-[10px] uppercase tracking-wider text-muted">{label}</span></Card>}
function DecisionDrawer({id,onClose,onDone}:{id:string|null;onClose:()=>void;onDone:()=>void}){const{token}=useAuth();const[comment,setComment]=useState("");const[error,setError]=useState("");const detail=useQuery({queryKey:["request-detail",id],queryFn:()=>api<RequestDetail>(`/api/v1/requests/${id}`,token),enabled:!!id});const action=useMutation({mutationFn:(kind:"approve"|"decline"|"complete")=>{if(kind==="decline"&&!comment.trim())throw new Error("A decline reason is required.");return api(`/api/v1/requests/${id}/${kind}`,token,{method:"POST",body:JSON.stringify({comment})})},onSuccess:onDone,onError:e=>setError(e instanceof Error?e.message:"Decision failed")});const r=detail.data?.request;return <Drawer open={!!id} onOpenChange={v=>!v&&onClose()} title={r?.type_label??"Request review"} description="Review the request, policy context, and timeline before deciding.">{detail.isLoading?<p className="text-muted">Loading request…</p>:r&&<div className="space-y-6"><div className="flex justify-between"><Badge tone={statusTone(r.status)}>{r.status}</Badge><span className="text-xs text-muted">#{r.id.slice(0,8)}</span></div><Card className="bg-ink/50"><dl className="grid grid-cols-2 gap-4 text-sm"><Item k="Employee" v={r.applicant}/><Item k="Duration" v={`${r.duration_days??"—"} days`}/><Item k="Starts" v={r.start_date??"—"}/><Item k="Ends" v={r.end_date??"—"}/></dl><p className="mt-5 border-t border-line pt-5 text-sm leading-6">{r.comment}</p></Card><section><h3 className="mb-4 text-xs font-bold uppercase tracking-wider text-muted">Timeline</h3><div className="space-y-0">{detail.data?.events.map((e,i)=><div key={e.id} className="relative flex gap-3 pb-5"><div className="relative z-10 mt-1 h-2.5 w-2.5 rounded-full bg-lime"/>{i<(detail.data?.events.length??0)-1&&<div className="absolute left-[4px] top-3 h-full w-px bg-line"/>}<div><p className="text-sm font-semibold">{e.to_status?.replace("_"," ")??e.event_type}</p><p className="mt-1 text-xs text-muted">{e.actor} · {new Date(e.created_at).toLocaleString()}</p></div></div>)}</div></section>{["submitted","in_review"].includes(r.status)&&<><textarea className={`${fieldClass} min-h-24`} value={comment} onChange={e=>setComment(e.target.value)} placeholder="Decision note. Required when declining." />{error&&<p className="text-sm text-danger">{error}</p>}<div className="grid grid-cols-2 gap-3"><Button onClick={()=>action.mutate("approve")} disabled={action.isPending}>Approve</Button><Button tone="danger" onClick={()=>action.mutate("decline")} disabled={action.isPending}>Decline</Button></div></>}{r.status==="approved"&&<Button className="w-full" onClick={()=>action.mutate("complete")}>Mark completed</Button>}</div>}</Drawer>}
function Item({k,v}:{k:string;v:string}){return <div><dt className="text-[10px] uppercase tracking-wider text-muted">{k}</dt><dd className="mt-1 font-semibold">{v}</dd></div>}
